routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\{
    FrontController
};
use App\Http\Controllers\Backend\{
    DashboardController,
    ManagerController,
    UserController,
    ConfigsController,
    PagesController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [FrontController::class, 'single'])->name('homepage');
// Route::get('/vendas', [FrontController::class, 'index'])->name('home');


// Route::get('/obrigado', [FrontController::class, 'obrigado'])->name('obrigado');;
// Route::post('/newcontact', [FrontController::class, 'newcontact'])->name('newcontact');;



Auth::routes();

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::resource('/', DashboardController::class);
    Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });

    Route::resource('users', UserController::class);
    Route::get('users/showsearch', [UserController::class, 'showsearch'])->name('users.showsearch');
    Route::post('users/search', [UserController::class, 'search'])->name('users.search');
    
    Route::get('configs', [ConfigsController::class, 'index'])->name('configs');
    Route::put('configs/{id}', [ConfigsController::class, 'update'])->name('configs.update');
    
    Route::resource('pages', PagesController::class);
    Route::get('pages/{slugPage}', [PagesController::class, 'show']);

});

app/Http/Controllers/Backend/ConfigsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Config;

class ConfigsController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.configs.'; // required ponto final

    public function index()
    {
        $config = Config::first();
        return view($this->folder . 'index', [
            'config' => $config
        ]);
    }

    public function update(Request $request, $id)
    {
        $model = new Config;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'meta_title'        => 'required',
            'meta_description'  => 'max:500',
            'name_site'         => 'required',
            'proprietary'       => 'required',
            'email_admin'       => 'required|email',
            'logo'              => 'nullable',
            'data_evento'              => 'nullable',
        ];

        $messages = [
            'meta_title.required' => 'título é obrigatório',
            'meta_description.max' => 'máximo de 500 caracteres',
            'name_site.required' => 'nome do site é obrigatório',
            'proprietary.required' => 'proprietário é obrigatório',
            'email_admin.required' => 'e-mail é obrigatório',
            'logo.required' => 'logo é obrigatório',
            'data_evento.required' => 'logo é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->name_site = $result['name_site'];
        $model->proprietary = $result['proprietary'];
        $model->address = $result['address'];
        $model->email_admin = $result['email_admin'];
        $model->telephone = $result['telephone'];
        $model->cellphone = $result['cellphone'];
        $model->hour_open = $result['hour_open'];
        $model->data_evento = $result['data_evento'];
        if($result['logo']){
            $format_url_logo = str_replace(env('APP_URL'), '', $result['logo']);
            $model->logo = $format_url_logo;
        }

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Configurações alteradas com sucesso', 200);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.';

    public function index(){
        return view($this->folder.'dashboard');
    }
}

app/Http/Controllers/Backend/PagesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\Models\Page;

class PagesController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.pages.';

    /**
     * Display a listing of the resource.
     * // INDEX
     */
    public function index(Request $request)
    {
        $itensPage = $request->input('itensPage') ? $request->input('itensPage') : '5';

        $pages = Page::paginate($itensPage);

        return view($this->folder . 'index', [
            'pages' => $pages,
            'itensPage' => $itensPage,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * // CREATE
     */
    public function create()
    {
        return view($this->folder . 'form');
    }

    /**
     * Store a newly created resource in storage.
     * // STORE
     */
    public function store(Request $request)
    {
        $model = new Page;
        $result = $request->all();

        $rules = [
            'meta_title'          => "required",
            'meta_description'    => "nullable|max:255",
            'meta_keywords'       => "nullable|max:255",
            'content'             => "required",
            'slug'                => "required|unique:pages",
            'status'              => "required",
        ];

        $messages = [
            'meta_title.required'       => 'título é obrigatório',
            'meta_description.max'      => 'descrição precisa ter no máximo 255 caracteres',
            'meta_keywords.max'         => 'palavras-chave precisa ter no máximo 255 caracteres',
            'content.required'          => 'conteúdo é obrigatório',
            'slug.required'             => 'url amigável é obrigatório',
            'slug.unique'               => 'url amigável já existe',
            'status.required'           => 'status é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->content = $result['content'];
        $model->slug = $result['slug'];
        $model->status = $result['status'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Pagina salva com sucesso', 200);
    }

    /**
     * Display the specified resource.
     * // SHOW
     */
    public function show($slugPage)
    {
        $page = new Page;
        $result = $page->where('slug', $slugPage)->first();

        return view($this->folder . 'show', compact('result'));
    }

    /**
     * Show the form for editing the specified resource.
     * // EDIT
     */
    public function edit($id)
    {
        $page = new Page;
        $result = $page->where('id', $id)->first();

        return view($this->folder . 'form', compact('result'));
    }

    /**
     * Update the specified resource in storage.
     * // UPDATE
     */
    public function update(Request $request, $id)
    {
        $model = new Page;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'meta_title'          => "required",
            'meta_description'    => "nullable|max:255",
            'meta_keywords'       => "nullable|max:255",
            'content'             => "required",
            'slug'                => "required|unique:pages,slug,$id,id",
            'status'              => "required",
        ];

        $messages = [
            'meta_title.required'       => 'título é obrigatório',
            'meta_description.max'      => 'descrição precisa ter no máximo 255 caracteres',
            'meta_keywords.max'         => 'palavras-chave precisa ter no máximo 255 caracteres',
            'content.required'          => 'conteúdo é obrigatório',
            'slug.required'             => 'url amigável é obrigatório',
            'slug.unique'               => 'url amigável já existe',
            'status.required'           => 'status é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->content = $result['content'];
        $model->slug = $result['slug'];
        $model->status = $result['status'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Pagina alterada com sucesso', 200);
    }

    /**
     * Remove the specified resource from storage.
     * // DESTROY
     */
    public function destroy($id)
    {
        $model = new Page;

        try {
            $find = $model->find($id);
            $find->delete();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json(true, 200);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.users.';

    /**
     * Display a listing of the resource.
     * // INDEX
     */
    public function index(Request $request)
    {
        $itensPage = $request->input('itensPage') ? $request->input('itensPage') : '5';

        $users = User::paginate($itensPage);

        return view($this->folder . 'index', [
            'users' => $users,
            'itensPage' => $itensPage,
        ]);
    }

    /**
     * Result Search.
     * // SEARCH
     */
    public function search(Request $request)
    {
        $output = null;
        $search = $request->input('search');

        if ($search) {
            $users = User::where('name', 'like', '%' . $search . '%')->orWhere('email', 'like',  '%' . $search . '%')->get();
        }else{
            return response()->json('Digite um nome ou e-mail', 422);
        }

        if(!$users->isEmpty()){
            foreach ($users as $key => $user) {
                $output .= '<tr>' .
                    '<td>' . $user->id . '</td>' .
                    '<td>' . $user->name . '</td>' .
                    '<td>' . $user->email . '</td>' .
                    '<td>' . \Carbon\Carbon::parse($user->created_at)->format('d/m/y H:i') . '</td>' .
                    '<td><a href="/dashboard/users/'.$user->id.'/edit" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                    <a href="javascript:;" data-id="' . $user->id . '" class="btn btn-sm btn-danger btn-delete"><i class="fa fa-trash"></i></a></td>' .
                    '</tr>';
            }
            return response()->json($output, 200);
        } else {
            return response()->json('Nenhum resultado foi encontrado.', 422);
        }
    }


    /**
     * Show the form for creating a new resource.
     * // CREATE
     */
    public function create()
    {
        return view($this->folder . 'form');
    }

    /**
     * Store a newly created resource in storage.
     * // STORE
     */
    public function store(Request $request)
    {
        $model = new User;
        $result = $request->all();

        $rules = [
            'name'          => "required",
            'email'         => "required|unique:users",
            'password'      => 'required|min:6|confirmed',
        ];

        $messages = [
            'name.required' => 'nome é obrigatório',
            'email.required' => 'e-mail é obrigatório',
            'password.required' => 'senha é obrigatório',
            'password.min' => 'senha precisa ter 6 caracteres',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->name = $result['name'];
        $model->email = $result['email'];
        $model->password = Hash::make($result['password']);

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Cliente salvo com sucesso', 200);
    }

    /**
     * Display the specified resource.
     * // SHOW
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * // EDIT
     */
    public function edit($id)
    {
        $user = new User;
        $result = $user->where('id', $id)->first();

        return view($this->folder . 'form', compact('result'));
    }

    /**
     * Update the specified resource in storage.
     * // UPDATE
     */
    public function update(Request $request, $id)
    {
        $model = new User;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'name'          => "required",
            'email'         => "unique:users,email,$id,id",
            'password'      => 'nullable|min:6|confirmed',
        ];

        $messages = [
            'name.required' => 'nome é obrigatório',
            'email.required' => 'e-mail é obrigatório',
            'email.unique' => 'e-mail já está em uso',
            'password.confirmed' => 'as senhas não são igual',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->name = $result['name'];
        $model->email = $result['email'];
        if ($result['password']) {
            $password = Hash::make($result['password']);
            $model->password = $password;
        }

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Cliente alterado com sucesso', 200);
    }

    /**
     * Remove the specified resource from storage.
     * // DESTROY
     */
    public function destroy($id)
    {
        $model = new User;

        try {
            $find = $model->find($id);
            $find->delete();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json(true, 200);
    }
}

resources/views/backend/pages/index.blade.php
@extends('backend.app')

@section('title', 'Paginas de Informações')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url('/dashboard') }}"><i class="fa fa-home"></i></a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="box">

                <div class="box-header with-border">
                    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center">
                        <div>
                            <h4 class="box-title">@yield('title')</h4>
                        </div>
                    </div>
                </div><!-- box-header -->

                <div class="box-body">
                    <!-- conteudo -->
                    <div class="table-responsive">
                        <table id="table-request" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Título</th>
                                    <th>Criado</th>
                                    <th>Status</th>
                                    <th width="150px"><i class="fa fa-cogs mr-2"></i> Ações</th>
                                </tr>
                            </thead>
                            <tbody id="table-body">
                                @foreach ($pages as $page)
                                    <tr id="row_{{ $page->id }}">
                                        <td>{{ $page->id }}</td>
                                        <td>{{ $page->meta_title }}</td>
                                        <td>{{ \Carbon\Carbon::parse($page->created_at)->format('d/m/y H:i') }}</td>
                                        <td>{{ $page->status }}</td>
                                        <td>
                                            <a href="{{ route('pages.show', $page->slug) }}"
                                                class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top"
                                                title="Ver Página"><i class="fa fa-eye"></i></a>

                                            <a href="{{ route('pages.edit', $page->id) }}" class="btn btn-sm btn-info"
                                                data-toggle="tooltip" data-placement="top" title="Editar Página"><i
                                                    class="fa fa-edit"></i></a>

                                            <a href="javascript:;" data-id="{{ $page->id }}"
                                                class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip"
                                                data-placement="top" title="Deletar Página?"><i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <hr class="m-4">
                    <div id="section-pagination"
                        class="d-flex flex-column flex-lg-row justify-content-between align-items-center">
                        <div class="mt-2 mt-lg-0">
                            <select name="itensPage" id="itensPage" class="form-control" data-toggle="tooltip"
                                data-placement="top" title="Quantidade por Página">
                                <option value="5" {{ $itensPage == '5' ? 'selected' : '' }}>5</option>
                                @for ($i = 10; $i < 50; $i += 10)
                                    <option value="{{ $i }}" {{ $itensPage == $i ? 'selected' : '' }}>
                                        {{ $i }}</option>
                                @endfor
                                <option value="50" {{ $itensPage == '50' ? 'selected' : '' }}>50</option>
                                <option value="100" {{ $itensPage == '100' ? 'selected' : '' }}>100</option>
                            </select>
                        </div>
                        {{ $pages->appends(request()->query())->links() }}
                    </div>
                    <!-- conteudo -->
                </div><!-- box-body -->

                <div class="box-footer flexbox">
                    <div class="text-left flex-grow">
                        <a href="{{ route('pages.create') }}" class="btn btn-rounded btn-success btn-mobile-float"
                            data-toggle="tooltip" data-placement="top" title="Nova Página"><i class="fa fa-plus"></i>
                            <span>Nova Página</span></a>
                    </div>
                </div><!-- box-footer -->

            </div><!-- box -->
        </div><!-- cols -->
    </div><!-- row -->
@endsection

@section('includeCSS')
    <!-- Include SweetAlert -->
    <link rel="stylesheet" href="{{ asset('/plugins/sweetalert/sweetalert2.min.css') }}">
@endsection

@section('includeJS')
    <!-- Include SweetAlert -->
    <script src="{{ asset('/plugins/sweetalert/sweetalert2.min.js') }}"></script>
    <script>
        // Run function Ready deleteUser -- solution before search
        $(document).ready(function() {
            deleteUser();
        });

        // Change Quantity Pagination
        $('#itensPage').on('change', function() {
            var itensPage = $(this).val();
            var url = '/dashboard/pages?itensPage=' + itensPage; // get selected value
            if (url) { // require a URL
                window.location = url; // redirect
            }
            return false;
        });

    </script>
    <script>
        // Button Search
        $(document).on('click', '#btn-search', function(e) {
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });
            var method = 'POST';
            var url = "{{ url('dashboard/pages/search') }}";
            var data = $('#form-search').serialize();

            $.ajax({
                url: url,
                data: data,
                method: method,
                success: function(data) {
                    $('.page-title, .box-title').html('Resultado da Busca')
                    $('#table-body').html('');
                    $('#section-pagination').html('');
                    $('#table-body').html(data);
                    deleteUser();
                },
                error: function(xhr) {
                    if (xhr.status === 422) {
                        Swal.fire({
                            text: xhr.responseJSON,
                            icon: 'info',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    } else {
                        Swal.fire({
                            text: 'Erro interno, informe ao suporte: ' + xhr.responseJSON,
                            icon: 'error',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    }
                }
            });
        });

    </script>
    <script>
        // Button - Delete - Not action Waiting
        function deleteUser() {
            $('.btn-delete').click(function(e) {
                console.log('cliquei')
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': "{{ csrf_token() }}"
                    }
                });
                let id = $(this).data('id');
                var url = `{{ url('dashboard/pages/${id}') }}`;

                Swal.fire({
                    title: 'Deseja remover este registro?',
                    text: "Você não poderá reverter isso!",
                    icon: 'question',
                    showCancelButton: true,
                    cancelButtonText: 'Cancelar',
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Sim, deletar!'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: url,
                            method: 'DELETE',
                            data: $('#form-table').serialize(),
                            success: function(data) {
                                // Loading page listagem
                                location.href = "{{ url('/dashboard/pages') }}";
                            },
                            error: function(xhr) {
                                if (xhr.status === 422) {
                                    Swal.fire({
                                        text: xhr.responseJSON,
                                        icon: 'warning',
                                        showClass: {
                                            popup: 'animate_animated animate_wobble'
                                        }
                                    });
                                } else {
                                    Swal.fire({
                                        text: xhr.responseJSON,
                                        icon: 'error',
                                        showClass: {
                                            popup: 'animate_animated animate_wobble'
                                        }
                                    });
                                }
                            }
                        });
                    }
                });
            });
        }

    </script>
@endsection

resources/views/backend/pages/show.blade.php
@extends('backend.app')

@section('title', 'Paginas - '.$result->meta_title)

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url('/dashboard') }}"><i class="fa fa-home"></i></a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="box">

                <div class="box-header with-border">
                    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center">
                        <div>
                            <h4 class="box-title">@yield('title')</h4>
                        </div>
                    </div>
                </div><!-- box-header -->

                <div class="box-body">
                    <!-- conteudo -->

                        {!! $result->content !!}
                                            
                    <!-- conteudo -->
                </div><!-- box-body -->

                <div class="box-footer flexbox">
                    <div class="text-left flex-grow">
                        <a href="{{ route('pages.edit', $result->id) }}" class="btn btn-rounded btn-primary btn-mobile-float"
                            data-toggle="tooltip" data-placement="top" title="Editar Página"><i
                                class="fa fa-edit"></i> <span>Editar Página</span></a>

                        <a href="{{ route('pages.index') }}" class="btn btn-sm btn-rounded btn-info"
                            data-toggle="tooltip" data-placement="top" title="Voltar"><i class="fa fa-angle-left"></i>
                            <span>Voltar</span></a>
                    </div>
                </div><!-- box-footer -->

            </div><!-- box -->
        </div><!-- cols -->
    </div><!-- row -->
@endsection