routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\{
    FrontController
};
use App\Http\Controllers\Backend\{
    DashboardController,
    ManagerController,
    UserController,
    ConfigsController,
    PagesController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [FrontController::class, 'single'])->name('homepage');
// Route::get('/vendas', [FrontController::class, 'index'])->name('home');


// Route::get('/obrigado', [FrontController::class, 'obrigado'])->name('obrigado');;
// Route::post('/newcontact', [FrontController::class, 'newcontact'])->name('newcontact');;



Auth::routes();

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::resource('/', DashboardController::class);
    Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });

    Route::resource('users', UserController::class);
    Route::get('users/showsearch', [UserController::class, 'showsearch'])->name('users.showsearch');
    Route::post('users/search', [UserController::class, 'search'])->name('users.search');
    
    Route::get('configs', [ConfigsController::class, 'index'])->name('configs');
    Route::put('configs/{id}', [ConfigsController::class, 'update'])->name('configs.update');
    
    Route::resource('pages', PagesController::class);
    Route::get('pages/{slugPage}', [PagesController::class, 'show']);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/ConfigsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Config;

class ConfigsController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.configs.'; // required ponto final

    public function index()
    {
        $config = Config::first();
        return view($this->folder . 'index', [
            'config' => $config
        ]);
    }

    public function update(Request $request, $id)
    {
        $model = new Config;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'meta_title'        => 'required',
            'meta_description'  => 'max:500',
            'name_site'         => 'required',
            'proprietary'       => 'required',
            'email_admin'       => 'required|email',
            'logo'              => 'nullable',
            'data_evento'              => 'nullable',
        ];

        $messages = [
            'meta_title.required' => 'título é obrigatório',
            'meta_description.max' => 'máximo de 500 caracteres',
            'name_site.required' => 'nome do site é obrigatório',
            'proprietary.required' => 'proprietário é obrigatório',
            'email_admin.required' => 'e-mail é obrigatório',
            'logo.required' => 'logo é obrigatório',
            'data_evento.required' => 'logo é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->name_site = $result['name_site'];
        $model->proprietary = $result['proprietary'];
        $model->address = $result['address'];
        $model->email_admin = $result['email_admin'];
        $model->telephone = $result['telephone'];
        $model->cellphone = $result['cellphone'];
        $model->hour_open = $result['hour_open'];
        $model->data_evento = $result['data_evento'];
        if($result['logo']){
            $format_url_logo = str_replace(env('APP_URL'), '', $result['logo']);
            $model->logo = $format_url_logo;
        }

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Configurações alteradas com sucesso', 200);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.';

    public function index(){
        return view($this->folder.'dashboard');
    }
}

app/Http/Controllers/Backend/PagesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\Models\Page;

class PagesController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.pages.';

    /**
     * Display a listing of the resource.
     * // INDEX
     */
    public function index(Request $request)
    {
        $itensPage = $request->input('itensPage') ? $request->input('itensPage') : '5';

        $pages = Page::paginate($itensPage);

        return view($this->folder . 'index', [
            'pages' => $pages,
            'itensPage' => $itensPage,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * // CREATE
     */
    public function create()
    {
        return view($this->folder . 'form');
    }

    /**
     * Store a newly created resource in storage.
     * // STORE
     */
    public function store(Request $request)
    {
        $model = new Page;
        $result = $request->all();

        $rules = [
            'meta_title'          => "required",
            'meta_description'    => "nullable|max:255",
            'meta_keywords'       => "nullable|max:255",
            'content'             => "required",
            'slug'                => "required|unique:pages",
            'status'              => "required",
        ];

        $messages = [
            'meta_title.required'       => 'título é obrigatório',
            'meta_description.max'      => 'descrição precisa ter no máximo 255 caracteres',
            'meta_keywords.max'         => 'palavras-chave precisa ter no máximo 255 caracteres',
            'content.required'          => 'conteúdo é obrigatório',
            'slug.required'             => 'url amigável é obrigatório',
            'slug.unique'               => 'url amigável já existe',
            'status.required'           => 'status é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->content = $result['content'];
        $model->slug = $result['slug'];
        $model->status = $result['status'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Pagina salva com sucesso', 200);
    }

    /**
     * Display the specified resource.
     * // SHOW
     */
    public function show($slugPage)
    {
        $page = new Page;
        $result = $page->where('slug', $slugPage)->first();

        return view($this->folder . 'show', compact('result'));
    }

    /**
     * Show the form for editing the specified resource.
     * // EDIT
     */
    public function edit($id)
    {
        $page = new Page;
        $result = $page->where('id', $id)->first();

        return view($this->folder . 'form', compact('result'));
    }

    /**
     * Update the specified resource in storage.
     * // UPDATE
     */
    public function update(Request $request, $id)
    {
        $model = new Page;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'meta_title'          => "required",
            'meta_description'    => "nullable|max:255",
            'meta_keywords'       => "nullable|max:255",
            'content'             => "required",
            'slug'                => "required|unique:pages,slug,$id,id",
            'status'              => "required",
        ];

        $messages = [
            'meta_title.required'       => 'título é obrigatório',
            'meta_description.max'      => 'descrição precisa ter no máximo 255 caracteres',
            'meta_keywords.max'         => 'palavras-chave precisa ter no máximo 255 caracteres',
            'content.required'          => 'conteúdo é obrigatório',
            'slug.required'             => 'url amigável é obrigatório',
            'slug.unique'               => 'url amigável já existe',
            'status.required'           => 'status é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->content = $result['content'];
        $model->slug = $result['slug'];
        $model->status = $result['status'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Pagina alterada com sucesso', 200);
    }

    /**
     * Remove the specified resource from storage.
     * // DESTROY
     */
    public function destroy($id)
    {
        $model = new Page;

        try {
            $find = $model->find($id);
            $find->delete();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json(true, 200);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.users.';

    /**
     * Display a listing of the resource.
     * // INDEX
     */
    public function index(Request $request)
    {
        $itensPage = $request->input('itensPage') ? $request->input('itensPage') : '5';

        $users = User::paginate($itensPage);

        return view($this->folder . 'index', [
            'users' => $users,
            'itensPage' => $itensPage,
        ]);
    }

    /**
     * Result Search.
     * // SEARCH
     */
    public function search(Request $request)
    {
        $output = null;
        $search = $request->input('search');

        if ($search) {
            $users = User::where('name', 'like', '%' . $search . '%')->orWhere('email', 'like',  '%' . $search . '%')->get();
        }else{
            return response()->json('Digite um nome ou e-mail', 422);
        }

        if(!$users->isEmpty()){
            foreach ($users as $key => $user) {
                $output .= '<tr>' .
                    '<td>' . $user->id . '</td>' .
                    '<td>' . $user->name . '</td>' .
                    '<td>' . $user->email . '</td>' .
                    '<td>' . \Carbon\Carbon::parse($user->created_at)->format('d/m/y H:i') . '</td>' .
                    '<td><a href="/dashboard/users/'.$user->id.'/edit" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                    <a href="javascript:;" data-id="' . $user->id . '" class="btn btn-sm btn-danger btn-delete"><i class="fa fa-trash"></i></a></td>' .
                    '</tr>';
            }
            return response()->json($output, 200);
        } else {
            return response()->json('Nenhum resultado foi encontrado.', 422);
        }
    }


    /**
     * Show the form for creating a new resource.
     * // CREATE
     */
    public function create()
    {
        return view($this->folder . 'form');
    }

    /**
     * Store a newly created resource in storage.
     * // STORE
     */
    public function store(Request $request)
    {
        $model = new User;
        $result = $request->all();

        $rules = [
            'name'          => "required",
            'email'         => "required|unique:users",
            'password'      => 'required|min:6|confirmed',
        ];

        $messages = [
            'name.required' => 'nome é obrigatório',
            'email.required' => 'e-mail é obrigatório',
            'password.required' => 'senha é obrigatório',
            'password.min' => 'senha precisa ter 6 caracteres',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->name = $result['name'];
        $model->email = $result['email'];
        $model->password = Hash::make($result['password']);

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Cliente salvo com sucesso', 200);
    }

    /**
     * Display the specified resource.
     * // SHOW
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * // EDIT
     */
    public function edit($id)
    {
        $user = new User;
        $result = $user->where('id', $id)->first();

        return view($this->folder . 'form', compact('result'));
    }

    /**
     * Update the specified resource in storage.
     * // UPDATE
     */
    public function update(Request $request, $id)
    {
        $model = new User;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'name'          => "required",
            'email'         => "unique:users,email,$id,id",
            'password'      => 'nullable|min:6|confirmed',
        ];

        $messages = [
            'name.required' => 'nome é obrigatório',
            'email.required' => 'e-mail é obrigatório',
            'email.unique' => 'e-mail já está em uso',
            'password.confirmed' => 'as senhas não são igual',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->name = $result['name'];
        $model->email = $result['email'];
        if ($result['password']) {
            $password = Hash::make($result['password']);
            $model->password = $password;
        }

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Cliente alterado com sucesso', 200);
    }

    /**
     * Remove the specified resource from storage.
     * // DESTROY
     */
    public function destroy($id)
    {
        $model = new User;

        try {
            $find = $model->find($id);
            $find->delete();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json(true, 200);
    }
}

resources/views/backend/users/form.blade.php
@extends('backend.app')

@section('title', isset($result) ? 'Editar Usuário - ' . $result->name : 'Novo Usuário')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url('/dashboard') }}"><i class="fa fa-home"></i></a>
        </li>
        <li class="breadcrumb-item" aria-current="page"><a href="{{ route('users.index') }}">Usuários Admin</a></li>
        <li class="breadcrumb-item active" aria-current="page">
            {{ isset($result) ? 'Editar Usuário' : 'Novo Usuário' }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="box">

                <div class="box-header with-border">
                    <h4 class="box-title">@yield('title')</h4>
                </div><!-- box-header -->

                <div class="box-body">
                    <!-- conteudo -->

                    <form id="form-request" method="POST" class="form-horizontal">
                        <div class="form-group">
                            <label for="name" class="col-sm-12">Nome:</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Digite seu Nome"
                                    value="{{ isset($result->name) ? $result->name : '' }}">
                            </div>
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label for="email" class="col-sm-12">E-mail Válido:</label>
                            <div class="col-sm-12">
                                <input type="email" class="form-control" id="email" name="email"
                                    placeholder="Digite seu E-mail"
                                    value="{{ isset($result->email) ? $result->email : '' }}">
                            </div>
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label for="password" class="col-sm-12">Senha:</label>
                            <div class="col-sm-12">
                                <input type="password" class="form-control" id="password" name="password"
                                    placeholder="Digite sua Senha de Acesso" value="">
                                <span class="help-block">* mínimo de 6 caracteres</span>
                            </div>
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label for="password_confirmation" class="col-sm-12">Confirmar Senha</label>
                            <div class="col-sm-12">
                                <input type="password" class="form-control" id="password_confirmation"
                                    name="password_confirmation" placeholder="Confirmar Senha">
                            </div>
                        </div><!-- form-group -->
                    </form>
                    <!-- conteudo -->
                </div><!-- box-body -->

                <div class="box-footer flexbox">
                    <div class="text-left flex-grow">
                        <a href="javascript:;" name="salvar" id="{{ isset($result) ? 'btn-edit' : 'btn-salvar' }}"
                            data-id="{{ isset($result) ? $result->id : '' }}" class="btn btn-rounded btn-success"><i
                                class="fa fa-check"></i> Salvar</a>
                        <a href="{{ route('users.index') }}" class="btn btn-sm btn-rounded btn-info" data-toggle="tooltip"
                            data-placement="top" title="Voltar"><i class="fa fa-angle-left"></i> <span>Voltar</span></a>
                    </div>
                </div><!-- box-footer -->

            </div><!-- box -->
        </div><!-- cols -->
    </div><!-- row -->
@endsection

@section('includeCSS')
    <!-- Include SweetAlert -->
    <link rel="stylesheet" href="{{ asset('/plugins/sweetalert/sweetalert2.min.css') }}">
@endsection

@section('includeJS')
    <!-- Include SweetAlert -->
    <script src="{{ asset('/plugins/sweetalert/sweetalert2.min.js') }}"></script>
    <script>
        $(document).on('click', '#btn-salvar', function(e) {
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });
            var method = 'POST';
            var url = "{{ route('users.store') }}";
            var data = $('#form-request').serialize();

            $.ajax({
                url: url,
                data: data,
                method: method,
                success: function(data) {
                    Swal.fire({
                        text: data,
                        icon: 'success',
                        showClass: {
                            popup: 'animate_animated animate_backInUp'
                        },
                        onClose: () => {
                            // Redirect Page Listagem
                            location.href = "{{ route('users.index') }}";
                        }
                    });
                },
                error: function(xhr) {
                    if (xhr.status === 422) {
                        Swal.fire({
                            text: 'Validação: ' + xhr.responseJSON,
                            icon: 'warning',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    } else {
                        Swal.fire({
                            text: 'Erro interno, informe ao suporte: ' + xhr.responseJSON,
                            icon: 'error',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    }
                }
            });
        });

    </script>
    <script>
        $(document).on('click', '#btn-edit', function(e) {
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });

            var data = $('#form-request').serialize();

            let id = $(this).data('id');
            var method = 'PUT';
            var url = `{{ url('dashboard/users/${id}') }}`;

            $.ajax({
                url: url,
                data: data,
                method: method,
                success: function(data) {
                    Swal.fire({
                        text: data,
                        icon: 'success',
                        showClass: {
                            popup: 'animate_animated animate_backInUp'
                        },
                        onClose: () => {
                            // Redirect Page Listagem
                            location.href = "{{ route('users.index') }}";
                        }
                    });
                },
                error: function(xhr) {
                    if (xhr.status === 422) {
                        Swal.fire({
                            text: 'Validação: ' + xhr.responseJSON,
                            icon: 'warning',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    } else {
                        Swal.fire({
                            text: 'Erro interno, informe ao suporte: ' + xhr.responseJSON,
                            icon: 'error',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    }
                }
            });
        });

    </script>
@endsection